<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineSwitchParser" />
    <PackageReference Include="System.ServiceModel.Syndication" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedModels\SharedModels.csproj" />
  </ItemGroup>

</Project>
