#!/usr/bin/env python3
"""Validate migrated CodeSnippet blocks against original gist content.

Reads gist-map.json (generated by migrate-gists.py), re-fetches each gist,
HTML-encodes it the same way the migrator does, and compares byte-for-byte
with the content found inside each <CodeSnippet> block in the migrated file.

Exit code: 0 = all OK, 1 = any mismatch or error.
"""

import json
import re
import ssl
import sys
import time
import urllib.request
from pathlib import Path

# ── SSL context ───────────────────────────────────────────────────────────────
try:
    import certifi
    _SSL_CTX = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    _SSL_CTX = ssl.create_default_context()

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent
GIST_MAP_FILE = Path(__file__).resolve().parent / "gist-map.json"

# ── Constants ─────────────────────────────────────────────────────────────────
RAW_URL_TEMPLATE = "https://gist.githubusercontent.com/{user}/{gist_id}/raw/"
HEADERS = {"User-Agent": "Mozilla/5.0 (validation-script/1.0)"}
RATE_LIMIT_DELAY = 0.3
DEFAULT_USER = "fingers10"

# Matches <CodeSnippet CssClass="...">...</CodeSnippet> across newlines (lazy)
CODE_SNIPPET_RE = re.compile(
    r'<CodeSnippet\s+CssClass="([^"]+)">(.*?)</CodeSnippet>',
    re.DOTALL,
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def fetch_raw(gist_id, user_id=DEFAULT_USER):
    url = RAW_URL_TEMPLATE.format(user=user_id, gist_id=gist_id)
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=30, context=_SSL_CTX) as resp:
        return resp.read().decode("utf-8", errors="replace")


def encode_for_razor(text):
    """Must match migrate-gists.py exactly — order is critical."""
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    text = text.replace("@", "@@")
    return text


def expected_inner(raw_content):
    """Produce the expected inner text of a CodeSnippet (mirrors migration logic)."""
    encoded = encode_for_razor(raw_content)
    if encoded.endswith("\n"):
        encoded = encoded[:-1]
    return encoded


def actual_inner(captured_group):
    """Extract the code from the regex capture group between CodeSnippet tags.

    Migration writes:
        <CodeSnippet CssClass="...">
        {encoded_content_without_last_newline}
        {indent}</CodeSnippet>

    So captured_group == "\n{content}\n{indent}"
    We strip the leading newline and the trailing newline+indent.
    """
    text = captured_group
    # Strip leading newline (after opening tag)
    if text.startswith("\n"):
        text = text[1:]
    # Strip trailing indent + newline (before closing tag)
    last_nl = text.rfind("\n")
    if last_nl != -1:
        text = text[:last_nl]
    return text


def show_diff(actual, expected, context=60):
    """Print the first point of difference between two strings."""
    min_len = min(len(actual), len(expected))
    for i in range(min_len):
        if actual[i] != expected[i]:
            start = max(0, i - context)
            end = min(min_len, i + context)
            print(f"    First diff at char index {i}:")
            print(f"    actual  : {actual[start:end]!r}")
            print(f"    expected: {expected[start:end]!r}")
            return
    if len(actual) != len(expected):
        print(f"    Lengths differ: actual={len(actual)}, expected={len(expected)}")
        if len(actual) > len(expected):
            print(f"    Extra in actual : {actual[min_len:min_len+80]!r}")
        else:
            print(f"    Extra in expected: {expected[min_len:min_len+80]!r}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not GIST_MAP_FILE.exists():
        print(f"❌ gist-map.json not found at {GIST_MAP_FILE}")
        print("   Run migrate-gists.py first.")
        sys.exit(1)

    gist_map = json.loads(GIST_MAP_FILE.read_text(encoding="utf-8"))

    ok_count = 0
    fail_count = 0
    error_count = 0

    for rel_path, gist_ids in gist_map.items():
        file_path = REPO_ROOT / rel_path
        print(f"\n📄 {rel_path}")

        if not file_path.exists():
            print(f"  ⚠  File not found — skipping")
            error_count += 1
            continue

        try:
            file_content = file_path.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"  ❌ Read error: {exc}")
            error_count += 1
            continue

        snippets = CODE_SNIPPET_RE.findall(file_content)  # list of (css_class, inner)

        if len(snippets) < len(gist_ids):
            print(
                f"  ❌ Expected {len(gist_ids)} CodeSnippet block(s), "
                f"found only {len(snippets)}"
            )
            fail_count += len(gist_ids)
            continue

        file_ok = True
        for idx, gist_id in enumerate(gist_ids):
            print(f"  [{idx + 1}/{len(gist_ids)}] {gist_id[:8]}...", end="  ")

            try:
                raw = fetch_raw(gist_id)
                time.sleep(RATE_LIMIT_DELAY)
            except Exception as exc:
                print(f"⚠  FETCH ERROR: {exc}")
                error_count += 1
                file_ok = False
                continue

            _, captured = snippets[idx]
            got = actual_inner(captured)
            want = expected_inner(raw)

            if got == want:
                print("✅")
                ok_count += 1
            else:
                print("❌ MISMATCH")
                show_diff(got, want)
                fail_count += 1
                file_ok = False

        status = "✅ all OK" if file_ok else "❌ has mismatches"
        print(f"  → {status}")

    print(f"\n{'=' * 60}")
    print(f"Results: {ok_count} ✅  |  {fail_count} ❌  |  {error_count} ⚠")
    total = ok_count + fail_count + error_count
    print(f"Total gist checks: {total}")

    if fail_count > 0 or error_count > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
