<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e837f286-a595-402e-9dd1-5d035762ef1c</UserSecretsId>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\MAUI\MAUI.csproj" /> -->
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Browsers" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="Aspire.Hosting.Maui" Version="13.4.6-preview.1.26319.6" />
  </ItemGroup>

</Project>
