<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SharedModels\SharedModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineSwitchParser" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
