name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Install Node JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.13.0'
      - run: npm install
        working-directory: ./Web
        
      # Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore
        
      # Build Project
      - name: Build
        run: dotnet build ./ILoveDotNet.sln --configuration Release --no-restore
        
      # Run Tests
      - name: Test
        run: dotnet test ./ILoveDotNet.sln --configuration Release --no-build --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
          retention-days: 3
          
      # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Web/Web.csproj -c Release --no-restore -o dist/Web --nologo
      
      # copy index.html to 404.html to serve the same file when a file is not found
      - name: Copy index.html to 404.html
        run: cp dist/Web/wwwroot/index.html dist/Web/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch dist/Web/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/Web/wwwroot
